### ISSUE TITLE
hwcomposer.kylin Source

### ISSUE THREAD

**Issue by erfanoabdi** [skoperst/android_device_sunxi_kylincommon#1]
Thanks for providing device tree.
But Source code of hwc is missing "hwcomposer.kylin" or i can't find it...

Check line 12:
https://github.com/skoperst/android_device_sunxi_kylincommon/blob/master/kylin-common.mk

thanks

**Comment by skoperst** [comment]
Sadly, I don't have this any more. 
Hope you can find it somewhere online.

**Comment by erfanoabdi** [comment]
thx for reply i found this https://github.com/pine64-android/hardware-aw/tree/master/hwc/kylin not sure works tho
